export var data = [
    {
        id: 1,
        name: 'Donny Jiang',
        category: 'Architecture',
        desc: 'Minneapolis, MN, USA',
        color: '#5f9199',
        url: './assets/img1.png',
    },
    {
        id: 2,
        name: 'Francesco Ungaro',
        category: 'Architecture',
        desc: 'Mudec museum of culture, Milano, Italy',
        color: '#426555',
        url: './assets/img2.png',
    },
    {
        id: 3,
        name: 'Dorien Monnens',
        category: 'Architecture',
        desc: 'Glasgow botanical garden',
        color: '#a2b3b0',
        url: './assets/img3.png',
    },
    {
        id: 4,
        name: 'Mehmet Turgut Kirkgoz',
        category: 'Architecture',
        desc: 'Vatican Museums, Vatikan',
        color: '#0d3d45',
        url: './assets/img4.png',
    },
    {
        id: 5,
        name: 'Clarisse Croset',
        category: 'Architecture',
        desc: 'Paris, France',
        color: '#807f7e',
        url: './assets/img5.png',
    },
    {
        id: 6,
        name: 'Dylan Leagh',
        category: 'Architecture',
        desc: 'Amsterdam',
        color: '#8da2a9',
        url: './assets/img6.png',
    },
    {
        id: 7,
        name: 'Thomas de LUZE',
        category: 'Architecture',
        desc: 'Slovénie, Slovénie',
        color: '#48737d',
        url: './assets/img7.png',
    },
    {
        id: 8,
        name: 'Nick Samoylov',
        category: 'Architecture',
        color: '#d89e80',
        desc: 'Dortheavej, Copenhagen, Denmark',
        url: './assets/img8.png',
    },
    {
        id: 9,
        name: 'Max Titov',
        category: 'Architecture',
        desc: 'Moscow City',
        color: '#6b0200',
        url: './assets/img9.png',
    },
    {
        id: 10,
        name: 'Duncan Meyer',
        desc: 'Hillcrest, South Africa',
        category: 'Architecture',
        color: '#858585',
        url: './assets/img10.png',
    },
    {
        id: 11,
        name: 'Andrea Ferrario',
        category: 'Architecture',
        desc: 'milano, Italia',
        color: '#3d656f',
        url: './assets/img11.png',
    },
    {
        id: 12,
        name: 'Franck V',
        desc: 'Intricate',
        category: 'Architecture',
        color: '#354578',
        url: './assets/img12.png',
    },
    {
        id: 13,
        name: 'Eugene Lim',
        category: 'Architecture',
        desc: 'Hong Kong Island, Hong Kong',
        color: '#303030',
        url: './assets/img13.png',
    },

    {
        id: 14,
        name: 'Zheni Yaneva',
        category: 'Architecture',
        desc: 'Canary Wharf, London, UK',
        color: '#5996ea',
        url: './assets/img14.png',
    },
    {
        id: 15,
        name: 'Jonathan Kemper',
        category: 'Architecture',
        desc: 'Bonn, Deutschland',
        color: '#736558',
        url: './assets/img15.png',
    },
];
